In [1]:
from diann_speclib_reader import *

In [2]:
lib = DiannLibrary()
lib.read(r"d:\AlphaDeepData\MaxDIA\diann\diann_fasta-lib.tsv.speclib")

100%|██████████| 131084/131084 [00:48<00:00, 2730.23it/s]

Elution groups loaded

In [3]:
lib.precursor_df

,lib_index,charge,nAA,mz,irt,srt,unknown,im,iim,frag_start_idx,frag_stop_idx,precursor_name,genes,proteins,proteotypic
0,0,3,0,795.386780,41.552338,0.0,2.322824e-03,0.0,0.0,0,12,AAAAAAAAAAAAAAAASAGGKEAASGPNDS3,SP9,P0CG40,1
1,1,2,0,798.927063,41.406906,0.0,1.557720e-07,0.0,0.0,12,21,AAAAAAAAAAAAAAAGAGAGAK2,SLC12A2,P55011,1
2,2,3,0,532.953979,42.722019,0.0,1.788385e-06,0.0,0.0,21,27,AAAAAAAAAAAAAAAGAGAGAK3,SLC12A2,P55011,1
3,3,3,0,790.075684,40.143509,0.0,5.028495e-05,0.0,0.0,27,36,AAAAAAAAAPAAAATAPTTAATTAATAAQ3,SRP14,P37108,1
4,4,2,0,500.781158,-11.252071,0.0,9.314952e-05,0.0,0.0,36,42,AAAAAAAAAVSR2,ZFP91,Q96JP5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131079,131079,2,0,663.285400,18.253633,0.0,5.028495e-05,0.0,0.0,1197406,1197412,YYYQGC(UniMod:4)ASWK2,XRN2,Q9H0D6,1
131080,131080,2,0,843.391113,68.600990,0.0,3.000948e-04,0.0,0.0,1197412,1197424,YYYVPADFVEYEK2,PHKB,Q93100,1
131081,131081,3,0,853.065002,42.193340,0.0,3.596023e-05,0.0,0.0,1197424,1197430,YYYVQNVYTPVDEHVYPDHR3,PEG10,Q86TG7,1
131082,131082,4,0,640.050720,37.884563,0.0,9.314952e-05,0.0,0.0,1197430,1197442,YYYVQNVYTPVDEHVYPDHR4,PEG10,Q86TG7,1
131083,131083,2,0,737.841919,45.696369,0.0,2.437043e-03,0.0,0.0,1197442,1197454,YYYWAVNPQDR2,LRBA,P50851,1

In [4]:
lib.fragment_df

                  mz  intensity  charge  frag_type  index  loss
0         569.304749   1.000000       1       -127      8     0
1         640.341858   0.957829       1          1      9     0
2         498.267609   0.912473       1          1      7     0
3         427.230499   0.847192       1       -127      6     0
4         711.378967   0.758138       1       -127     10     0
...              ...        ...     ...        ...    ...   ...
1197449   747.314209   0.045397       1       -127      5     0
1197450   676.277100   0.031346       1       -127      4     0
1197451  1311.612793   0.029051       1       -126      1     0
1197452   493.246979   0.016840       2       -126      3     0
1197453   846.382629   0.015085       1       -127      6     0

[1197454 rows x 6 columns]

In [5]:
lib.fragment_df.intensity.min()

0.0006598522886633873

In [7]:
(lib.precursor_df.frag_stop_idx-lib.precursor_df.frag_start_idx).min()

4

In [8]:
from alphabase.io.hdf import HDF_File

hdf = HDF_File(
    r"d:\AlphaDeepData\MaxDIA\diann\diann_lib.hdf",
    read_only=False, 
    delete_existing=True
)
hdf.precursor_df = lib.precursor_df
hdf.fragment_df = lib.fragment_df